import { execFileSync } from 'node:child_process'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

/**
 * `modules/cloud/aws/cdn/error-status-demote.zip` is a COMMITTED Lambda@Edge
 * deployment package, deliberately not generated by a Terraform
 * `data "archive_file"` — see the comment above
 * `aws_lambda_function.error_status_demote` in infra/global/main.tf and
 * `modules/cloud/aws/compute/main.tf`'s placeholder.zip for the prior
 * incident (#1457) this avoids: `deploy-infra.yml` runs `plan` and `apply` as
 * separate jobs on separate runners, transporting only the saved `tfplan` —
 * a zip written to disk by a data source at plan time does not exist on the
 * apply runner, and `aws_lambda_function`'s `filename` argument is read from
 * local disk by the AWS provider at apply time, not embedded in the plan.
 *
 * Committing the zip removes that coupling, but trades it for a DIFFERENT
 * risk `placeholder.zip` doesn't have: that zip is inert (real code arrives
 * via a separate CI deploy step), so it never goes stale relative to
 * anything. This one IS the real, only deployed artifact for
 * error-status-demote.js — nothing else ships its code — so if the zip and
 * the source ever diverge, Lambda@Edge silently keeps running old logic
 * after `error-status-demote.js` is edited and merged, with no red build to
 * say so. This test is that guard: it unzips the committed archive and
 * asserts its one entry is byte-identical to the current source file.
 *
 * To regenerate after editing error-status-demote.js:
 *   cd modules/cloud/aws/cdn && zip -j -X error-status-demote.zip error-status-demote.js
 */
const repoRoot = join(__dirname, '..', '..', '..')
const cdnDir = join(repoRoot, 'modules', 'cloud', 'aws', 'cdn')
const zipPath = join(cdnDir, 'error-status-demote.zip')
const sourcePath = join(cdnDir, 'error-status-demote.js')

describe('error-status-demote.zip stays in sync with error-status-demote.js', () => {
  it('contains exactly one entry, named error-status-demote.js', () => {
    const listing = execFileSync('unzip', ['-Z1', zipPath], { encoding: 'utf8' }).trim().split('\n')
    expect(listing).toEqual(['error-status-demote.js'])
  })

  it('that entry is byte-identical to the current source file', () => {
    const zipped = execFileSync('unzip', ['-p', zipPath, 'error-status-demote.js'], {
      encoding: 'utf8',
    })
    const source = readFileSync(sourcePath, 'utf8')
    expect(zipped).toBe(source)
  })
})
