"""Executing an agent run's write-back (ADR-0027 §2, §5, §7).

This is the security-critical half of write-back, and its shape is deliberate:
**the orchestrator triggers, Core decides and executes.** The internal route that
calls in here is handed an agent-run id and nothing else. Target table, operation,
column set, values, row selection and the principal to act as are all resolved
here from state Core already holds, so a buggy or compromised plugin cannot name
a table, pick a column, supply a value or choose an identity.

That hardens by one step the rule ``owner_data_handlers`` already follows for
ADR-0017 §5 — *the owner is taken from the verified token, never from the
request* — because an asynchronous completion has no live token to forward at
all. Hence the stored principal, and hence :func:`bind_principal_session`.

Ordering matters and is not incidental:

1. an ungranted target is **404**, indistinguishable from one that does not
   exist (ADR-0004 §4), so a workflow cannot probe what else is writeable;
2. the run is **claimed** before anything is written, so a redelivered
   completion event cannot double-write;
3. the session is **bound to the stored author** before the statement, and a
   refusal aborts — the write never runs on an unbound session;
4. every refusal is **recorded**, because a denial nobody can see is
   indistinguishable from a feature that silently stopped working.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from aws_lambda_powertools import Logger
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError, SQLAlchemyError
from sqlalchemy.ext.asyncio import AsyncSession

from .identity import get_identity_provider
from .models.agent_run import AgentRun
from .models.orchestration import ActionLog, WorkflowDefinition, WorkflowRun
from .routing.crud_handlers import _emit_crud_event, _event_payload
from .writeback_targets import (
    DerivedValue,
    WriteBackColumn,
    WriteBackTarget,
    bind_principal_session,
    resolve_writeback_target,
)

logger = Logger()

#: The action type recorded on the audit log for a write-back.
WRITEBACK_ACTION = "writeback"

#: How many consecutive denials before a definition disables itself. A workflow
#: whose owner has left should stop trying, visibly, rather than generating a
#: denial per event forever.
MAX_CONSECUTIVE_DENIALS = 3


class WriteBackNotFoundError(Exception):
    """The run, or the target it names, is not reachable by this caller.

    Deliberately one exception for both: the router answers 404, so "no such
    run" and "not a target you may write" are indistinguishable.
    """


@dataclass(frozen=True)
class WriteBackOutcome:
    """What happened, in a shape the router can return and a human can read."""

    status: str  # "written" | "skipped" | "denied" | "duplicate"
    run_id: str | None = None
    row_id: str | None = None
    reason: str | None = None

    @property
    def wrote(self) -> bool:
        return self.status == "written"


def _dedupe_key(agent_run_id: str) -> str:
    """One write per agent run, forever.

    Reuses the orchestration run's existing unique ``(tenant_id, dedupe_key)``
    constraint rather than adding a claims table, which is what makes write-back
    exactly-once for free — and, being a real run, auditable rather than merely
    logged (closing the gap ADR-0020 accepted for messages).
    """
    return f"writeback:{agent_run_id}"


def _submitted_values(run: AgentRun) -> dict[str, Any]:
    """The columns the agent submitted, from its structured result.

    A write-back run's output tool is generated by Core from the ceiling (§6), so
    a well-behaved run's ``result`` is exactly that object. Anything else — a
    prose ``output``, a missing result — yields nothing to write, which the
    caller turns into a skip rather than a half-written row.
    """
    result = run.result
    if not isinstance(result, dict):
        return {}
    # The submit-tool path stores the tool's arguments as the result itself; the
    # plain-completion path stores {"output": "..."} , which carries no columns.
    if "output" in result and len(result) == 1:
        return {}
    return {k: v for k, v in result.items() if k != "output"}


def _coerce(column: WriteBackColumn, value: Any) -> Any:
    """Coerce a submitted value to the column's declared type, or ``None``.

    Returning ``None`` for an unusable value (rather than raising) lets an
    optional column simply go unset when the model returned nonsense, while a
    required column's absence is caught by the caller. An ``enum`` value outside
    the declared set is dropped: the schema already told the model what was
    allowed, so anything else is a violation, not a preference.
    """
    if value is None:
        return None
    if column.type == "boolean":
        return bool(value)
    if column.type == "number":
        try:
            return float(value)
        except (TypeError, ValueError):
            return None
    text = str(value)
    if column.type == "enum" and text not in column.values:
        return None
    return text


def _derived_value(derived: DerivedValue, *, tenant_id: str, scope: dict[str, Any] | None) -> Any:
    """Resolve one Core-set column from trusted state (ADR-0027 §4)."""
    if derived.kind == "from_tenant":
        return tenant_id
    if derived.kind == "literal":
        return derived.value
    # from_scope — the definition's *validated* scope, which the authoring gate
    # already checked the author may act on. This is the value an instance's row
    # policies evaluate, which is exactly why it may not come from the model.
    if scope is None or scope.get("level") != derived.level:
        return None
    return scope.get("id")


def _apply_overwrite(column: WriteBackColumn, existing: Any, incoming: Any) -> Any:
    """What an update writes, given what is already there.

    ``if_empty`` (the default) is the reason this exists: an agent enriching a
    record must not clobber what a person typed unless the target explicitly
    says it may.
    """
    if incoming is None:
        return existing
    if column.overwrite == "always":
        return incoming
    if existing in (None, ""):
        return incoming
    if column.overwrite == "append":
        return f"{existing}\n\n{incoming}"
    return existing  # if_empty, and it isn't


async def _record(
    db: AsyncSession,
    *,
    tenant_id: str,
    run_id: str | None,
    status: str,
    response: dict[str, Any] | None = None,
    error: str | None = None,
) -> None:
    """Write the audit row. ``request`` is deliberately never populated — it
    would echo the action config, which can carry a credential (#432)."""
    if run_id is None:
        return
    db.add(
        ActionLog(
            tenant_id=tenant_id,
            run_id=run_id,
            action_type=WRITEBACK_ACTION,
            status=status,
            response=response,
            error=error,
        )
    )
    await db.flush()


async def _deny(
    db: AsyncSession,
    *,
    tenant_id: str,
    run_id: str | None,
    definition: WorkflowDefinition | None,
    reason: str,
) -> WriteBackOutcome:
    """Record a refusal, and disable a definition that keeps being refused.

    A denial that only appears in logs is indistinguishable from a feature that
    silently stopped working, so it lands on the audit log the run history
    already reads. Repeated denials disable the rule: a workflow whose owner has
    left should stop trying, loudly, rather than emitting one denial per event
    forever.
    """
    logger.warning("Write-back denied", extra={"agent_run_id": run_id, "reason": reason})
    await _record(db, tenant_id=tenant_id, run_id=run_id, status="failed", error=reason)
    if definition is not None:
        recent = await db.execute(
            select(ActionLog)
            .where(
                ActionLog.tenant_id == tenant_id,
                ActionLog.action_type == WRITEBACK_ACTION,
            )
            .order_by(ActionLog.created_at.desc())
            .limit(MAX_CONSECUTIVE_DENIALS)
        )
        rows = list(recent.scalars())
        if len(rows) >= MAX_CONSECUTIVE_DENIALS and all(r.status == "failed" for r in rows):
            definition.enabled = False
            await db.flush()
            logger.warning(
                "Write-back workflow disabled after consecutive denials",
                extra={"definition_id": definition.id},
            )
    return WriteBackOutcome(status="denied", run_id=run_id, reason=reason)


async def _resolve_definition(
    db: AsyncSession, *, tenant_id: str, run: AgentRun
) -> WorkflowDefinition | None:
    """The definition that requested this run, via its orchestration run.

    ``None`` when the chain is broken — the agent run was created outside a
    workflow, or the definition has since been deleted. Either way there is no
    principal to act as, so the caller denies rather than guessing one.
    """
    if not run.workflow_run_id:
        return None
    workflow_run = (
        await db.execute(
            select(WorkflowRun).where(
                WorkflowRun.tenant_id == tenant_id, WorkflowRun.id == run.workflow_run_id
            )
        )
    ).scalar_one_or_none()
    if workflow_run is None:
        return None
    return (
        await db.execute(
            select(WorkflowDefinition).where(
                WorkflowDefinition.tenant_id == tenant_id,
                WorkflowDefinition.id == workflow_run.definition_id,
            )
        )
    ).scalar_one_or_none()


async def _claim(
    db: AsyncSession,
    *,
    tenant_id: str,
    definition_id: str,
    agent_run_id: str,
    event: dict[str, Any],
) -> tuple[WorkflowRun, bool]:
    """Create-or-get the run recording this write-back. ``(run, created)``.

    Same SAVEPOINT idiom as the orchestration claim: a duplicate rolls back only
    the insert, and the existing run comes back with ``created=False`` so the
    caller writes nothing a second time.
    """
    key = _dedupe_key(agent_run_id)
    run = WorkflowRun(
        tenant_id=tenant_id,
        definition_id=definition_id,
        dedupe_key=key,
        trigger_event=event,
        status="dispatched",
    )
    try:
        async with db.begin_nested():
            db.add(run)
            await db.flush()
    except IntegrityError:
        existing = await db.execute(
            select(WorkflowRun).where(
                WorkflowRun.tenant_id == tenant_id, WorkflowRun.dedupe_key == key
            )
        )
        return existing.scalar_one(), False
    return run, True


def _emit_state_change(
    db: AsyncSession,
    *,
    target: WriteBackTarget,
    operation: str,
    tenant_id: str,
    row: Any,
    agent_run: AgentRun,
) -> None:
    """Emit the table's state-change event, carrying the causation chain.

    Reuses the generic-CRUD emitter so the payload is the same full-row,
    secret-denylisted shape every other mutation produces — a consumer cannot
    tell an agent's write from a person's, which is right: it is the same
    mutation.

    The chain is the addition that matters. A workflow that writes a lead and is
    itself triggered by ``leads.created`` would otherwise cycle; inheriting
    ``causation_id`` and ``depth + 1`` from the agent run puts that loop under
    ADR-0014 §8's existing depth ceiling instead of leaving it unbounded.
    """
    op = "created" if operation == "create" else "updated"
    payload = _event_payload_for(target, row)
    payload.update(
        {
            "causation_id": agent_run.causation_id or agent_run.id,
            "depth": agent_run.depth + 1,
            "written_by": "agent",
        }
    )
    _emit_crud_event(db, target.model, op, tenant_id, row=row, payload=payload)


def _event_payload_for(target: WriteBackTarget, row: Any) -> dict[str, Any]:
    """The row as the CRUD emitter would serialise it."""
    exclude = frozenset(getattr(target.model, "__event_exclude__", ()) or ())
    return _event_payload(row, exclude)


async def execute_writeback(
    db: AsyncSession,
    *,
    tenant_id: str,
    agent_run_id: str,
    principal_names: frozenset[str],
) -> WriteBackOutcome:
    """Record a completed agent run's result into its declared target.

    Everything but ``agent_run_id`` comes from stored state; see the module
    docstring for why. Raises :class:`WriteBackNotFoundError` for anything this
    caller must not be able to distinguish from a nonexistent run.
    """
    agent_run = (
        await db.execute(
            select(AgentRun).where(AgentRun.tenant_id == tenant_id, AgentRun.id == agent_run_id)
        )
    ).scalar_one_or_none()
    if agent_run is None:
        raise WriteBackNotFoundError(agent_run_id)

    if agent_run.status != "completed":
        return WriteBackOutcome(status="skipped", reason="the run did not succeed")

    declared = (agent_run.definition_snapshot or {}).get("writeback")
    if not isinstance(declared, dict) or not declared:
        return WriteBackOutcome(status="skipped", reason="the run declared no write-back")

    target = resolve_writeback_target(str(declared.get("table") or ""))
    # An ungranted or unregistered target must look nonexistent, so a plugin the
    # table never named cannot even learn that it exists.
    if target is None or not target.allows(principal_names):
        raise WriteBackNotFoundError(agent_run_id)

    operation = str(declared.get("operation") or "create")
    if operation not in target.operations:
        return await _deny(
            db,
            tenant_id=tenant_id,
            run_id=None,
            definition=None,
            reason=f"{target.label} does not allow {operation}",
        )

    definition = await _resolve_definition(db, tenant_id=tenant_id, run=agent_run)
    if definition is None:
        return WriteBackOutcome(
            status="skipped",
            reason="the workflow that requested this run no longer exists",
        )

    # ── Authority ────────────────────────────────────────────────────────────
    run_as = definition.run_as_user_id
    if not run_as:
        return await _deny(
            db,
            tenant_id=tenant_id,
            run_id=None,
            definition=definition,
            reason="the workflow records no owner, so the write has no authority to run under",
        )

    # Re-check the author's *current* permissions. This is not the authorization
    # — the row policies are — but it turns the common refusal into a legible
    # message instead of a raw policy violation. An empty set means this
    # deployment does not model permissions this way (the default provider
    # returns one for everybody), so it is not read as a denial: absence of
    # evidence is not evidence of absence, and the policies still decide.
    permissions = await get_identity_provider().resolve_permissions(db, run_as)
    if permissions and target.permission_code not in permissions:
        return await _deny(
            db,
            tenant_id=tenant_id,
            run_id=None,
            definition=definition,
            reason=(
                f"the workflow's owner no longer has permission to write to {target.label} "
                f"({target.permission_code})"
            ),
        )

    # ── Claim, then write ────────────────────────────────────────────────────
    workflow_run, created = await _claim(
        db,
        tenant_id=tenant_id,
        definition_id=definition.id,
        agent_run_id=agent_run_id,
        event=agent_run.input_payload or {},
    )
    if not created:
        return WriteBackOutcome(
            status="duplicate",
            run_id=workflow_run.id,
            reason="this run has already been recorded",
        )

    submitted = _submitted_values(agent_run)
    allowed = {c.name for c in target.columns if c.name in declared.get("columns", {})}
    values = {
        column.name: _coerce(column, submitted.get(column.name))
        for column in target.columns
        if column.name in allowed
    }
    missing = [
        c.name
        for c in target.columns
        if c.required and c.name in allowed and not values.get(c.name)
    ]
    if missing:
        return await _deny(
            db,
            tenant_id=tenant_id,
            run_id=workflow_run.id,
            definition=definition,
            reason=f"the agent returned no value for required column(s) {missing}",
        )

    # The session must act as the stored author before anything is written. A
    # refusal — including the template's own default, which has no row-level
    # security to bind to — aborts here rather than writing on an unbound session
    # where no policy would scope it.
    if not await bind_principal_session(db, run_as):
        return await _deny(
            db,
            tenant_id=tenant_id,
            run_id=workflow_run.id,
            definition=definition,
            reason=(
                "this deployment cannot bind a database session to the workflow's owner, "
                "so the write could not be authorized"
            ),
        )

    try:
        if operation == "create":
            row = await _create_row(
                db, target=target, tenant_id=tenant_id, scope=definition.scope, values=values
            )
        else:
            row = await _update_row(
                db,
                target=target,
                tenant_id=tenant_id,
                values=values,
                event=agent_run.input_payload or {},
            )
    except SQLAlchemyError as exc:
        # A row policy refusing the write arrives here (PostgreSQL 42501). It is
        # the expected outcome when the owner's authority has been taken away,
        # so it is a recorded denial, not a 500.
        return await _deny(
            db,
            tenant_id=tenant_id,
            run_id=workflow_run.id,
            definition=definition,
            reason=(
                f"the database refused the write for the workflow's owner: {exc.__class__.__name__}"
            ),
        )

    if row is None:
        return await _deny(
            db,
            tenant_id=tenant_id,
            run_id=workflow_run.id,
            definition=definition,
            reason="no matching row the workflow's owner is allowed to see",
        )

    _emit_state_change(
        db,
        target=target,
        operation=operation,
        tenant_id=tenant_id,
        row=row,
        agent_run=agent_run,
    )
    row_id = getattr(row, "id", None)
    workflow_run.status = "succeeded"
    await _record(
        db,
        tenant_id=tenant_id,
        run_id=workflow_run.id,
        status="succeeded",
        response={"table": target.table, "operation": operation, "row_id": row_id},
    )
    return WriteBackOutcome(status="written", run_id=workflow_run.id, row_id=row_id)


async def _create_row(
    db: AsyncSession,
    *,
    target: WriteBackTarget,
    tenant_id: str,
    scope: dict[str, Any] | None,
    values: dict[str, Any],
) -> Any:
    """Insert, with Core-set columns taken from trusted state, never the model."""
    fields = {name: value for name, value in values.items() if value is not None}
    for derived in target.derived:
        resolved = _derived_value(derived, tenant_id=tenant_id, scope=scope)
        if resolved is not None:
            fields[derived.column] = resolved
    row = target.model(**fields)
    db.add(row)
    await db.flush()
    # Refresh before the caller serialises it for the state-change event: a
    # flushed instance can still hold expired attributes, and reading one during
    # payload building would lazy-load outside the async context.
    await db.refresh(row)
    return row


async def _update_row(
    db: AsyncSession,
    *,
    target: WriteBackTarget,
    tenant_id: str,
    values: dict[str, Any],
    event: dict[str, Any],
) -> Any:
    """Amend the row the *trigger event* identified — never one the agent chose.

    Selection runs on the bound session, so an instance's row policies decide
    which rows exist at all: a row the owner cannot see is simply not found, and
    the caller records a denial rather than writing.
    """
    selector = target.row_selector
    if selector is None:  # pragma: no cover — registration refuses this
        return None
    row_id = event.get(selector.payload_field)
    if not row_id:
        return None
    column = getattr(target.model, selector.column)
    row = (
        await db.execute(
            select(target.model).where(
                target.model.tenant_id == tenant_id,  # type: ignore[attr-defined]
                column == row_id,
            )
        )
    ).scalar_one_or_none()
    if row is None:
        return None
    for spec in target.columns:
        if spec.name not in values:
            continue
        merged = _apply_overwrite(spec, getattr(row, spec.name, None), values[spec.name])
        setattr(row, spec.name, merged)
    await db.flush()
    await db.refresh(row)
    return row
