"""Executing an agent run's write-back (ADR-0027 §2, §5, §7).

This is the security-critical half of write-back, and its shape is deliberate:
**the orchestrator triggers, Core decides and executes.** The internal route that
calls in here is handed an agent-run id and nothing else. Target table, operation,
column set, values, row selection and the principal to act as are all resolved
here from state Core already holds, so a buggy or compromised plugin cannot name
a table, pick a column, supply a value or choose an identity.

That hardens by one step the rule ``owner_data_handlers`` already follows for
ADR-0017 §5 — *the owner is taken from the verified token, never from the
request* — because an asynchronous completion has no live token to forward at
all. Hence the stored principal, and hence :func:`bind_principal_session`.

Ordering matters and is not incidental:

1. an ungranted target is **404**, indistinguishable from one that does not
   exist (ADR-0004 §4), so a workflow cannot probe what else is writeable;
2. the run is **claimed** before anything is written, so a redelivered
   completion event cannot double-write;
3. the session is **bound to the stored author** before the statement, and a
   refusal aborts — the write never runs on an unbound session;
4. every refusal is **recorded**, because a denial nobody can see is
   indistinguishable from a feature that silently stopped working.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from aws_lambda_powertools import Logger
from pydantic_core import to_jsonable_python
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError, SQLAlchemyError
from sqlalchemy.ext.asyncio import AsyncSession

from .config import settings
from .identity import get_identity_provider
from .models.agent_run import AgentRun
from .models.orchestration import ActionLog, WorkflowDefinition, WorkflowRun
from .routing.crud_handlers import _emit_crud_event, _event_payload
from .writeback_targets import (
    DerivedValue,
    WriteBackColumn,
    WriteBackTarget,
    bind_principal_session,
    redactable_columns,
    resolve_writeback_target,
)

logger = Logger()

#: The action type recorded on the audit log for a write-back.
WRITEBACK_ACTION = "writeback"

#: Removed in favour of ``settings.writeback_max_consecutive_denials`` (#680).
#:
#: Read at call time rather than captured here at import: nothing outside this
#: module imported the old constant, so there was no compatibility reason to keep
#: a module attribute, and a call-time read is the one a test can monkeypatch.


class WriteBackNotFoundError(Exception):
    """The run, or the target it names, is not reachable by this caller.

    Deliberately one exception for both: the router answers 404, so "no such
    run" and "not a target you may write" are indistinguishable.
    """


@dataclass(frozen=True)
class WriteBackOutcome:
    """What happened, in a shape the router can return and a human can read."""

    status: str  # "written" | "skipped" | "denied" | "duplicate"
    run_id: str | None = None
    row_id: str | None = None
    reason: str | None = None

    @property
    def wrote(self) -> bool:
        return self.status == "written"


def _dedupe_key(agent_run_id: str) -> str:
    """One write per agent run, forever.

    Reuses the orchestration run's existing unique ``(tenant_id, dedupe_key)``
    constraint rather than adding a claims table, which is what makes write-back
    exactly-once for free — and, being a real run, auditable rather than merely
    logged (closing the gap ADR-0020 accepted for messages).
    """
    return f"writeback:{agent_run_id}"


def _submitted_values(run: AgentRun) -> dict[str, Any]:
    """The columns the agent submitted, from its structured result.

    A write-back run's output tool is generated by Core from the ceiling (§6),
    and the runtime records a submit-tool call as::

        {"output_tool": "submit_leads_record",
         "arguments": {...the columns...},
         "model": ..., "turns": ..., "finish_reason": ...}

    So the columns live under ``arguments`` — the sibling keys are run metadata,
    not data. Reading the top level instead silently matched no column, wrote
    nothing, and still reported success (#249 follow-up); the shape is asserted
    here against ``agent_runtime.loop``'s writer rather than assumed.

    A plain-completion result (``{"output": "..."}``) carries no columns, which
    the caller turns into a refusal rather than a half-written row.
    """
    result = run.result
    if not isinstance(result, dict):
        return {}
    arguments = result.get("arguments")
    if isinstance(arguments, dict):
        return dict(arguments)
    # Back-compat: a result whose columns sit at the top level, and which is not
    # the prose-completion shape.
    if "output" in result:
        return {}
    return {k: v for k, v in result.items() if k not in _RUN_METADATA_KEYS}


#: Keys the runtime attaches to a result that describe the *run*, never the row.
_RUN_METADATA_KEYS = frozenset({"output", "output_tool", "model", "turns", "finish_reason"})


def _coerce(column: WriteBackColumn, value: Any) -> Any:
    """Coerce a submitted value to the column's declared type, or ``None``.

    Returning ``None`` for an unusable value (rather than raising) lets an
    optional column simply go unset when the model returned nonsense, while a
    required column's absence is caught by the caller. An ``enum`` value outside
    the declared set is dropped: the schema already told the model what was
    allowed, so anything else is a violation, not a preference.
    """
    if value is None:
        return None
    if column.type == "boolean":
        return bool(value)
    if column.type == "number":
        try:
            return float(value)
        except (TypeError, ValueError):
            return None
    text = str(value)
    if column.type == "enum" and text not in column.values:
        return None
    return text


async def _derived_value(
    derived: DerivedValue,
    *,
    db: AsyncSession,
    tenant_id: str,
    scope: dict[str, Any] | None,
    event: dict[str, Any] | None = None,
) -> Any:
    """Resolve one Core-set column from trusted state (ADR-0027 §4).

    Async because ``from_lookup`` (#672) is: the only kind here that reads the
    database rather than state already carried on ``tenant_id``/``scope``/
    ``event``. It runs on ``db`` as handed to this function — the caller
    (``_create_row``) is only ever reached after ``bind_principal_session`` has
    succeeded, so the lookup is on the same RLS-bound session the insert itself
    uses and can never see past what the workflow's owner may.
    """
    if derived.kind == "from_tenant":
        return tenant_id
    if derived.kind == "literal":
        return derived.value
    # from_payload — the trigger event, which was settled before the model
    # produced anything. Same rule as RowSelector, one level up: a create's
    # parent keys decide which row it belongs to and which policies judge it, so
    # they can no more come from the agent than an update's target row can.
    if derived.kind == "from_payload":
        value = (event or {}).get(derived.payload_field or "")
        return value if value not in (None, "") else None
    # from_lookup — a database read on the bound session, never the model's
    # output. `resolver` is validated non-None at registration (#672).
    if derived.kind == "from_lookup":
        if derived.resolver is None:  # pragma: no cover — registration refuses this
            return None
        return await derived.resolver(db, tenant_id, scope)
    # from_scope — the definition's *validated* scope, which the authoring gate
    # already checked the author may act on. This is the value an instance's row
    # policies evaluate, which is exactly why it may not come from the model.
    if scope is None or scope.get("level") != derived.level:
        return None
    return scope.get("id")


def _coerce_selector(column: Any, value: Any) -> Any:
    """Cast the selector value to the column's own Python type.

    A trigger payload is JSON, so the row id always arrives as a **string**. The
    column it identifies need not be one — tabsii's are ``UUID``. PostgreSQL's
    driver coerces that silently, so this looks unnecessary there; SQLite does
    not, and neither dialect should be the thing deciding whether a workflow can
    find its row.
    """
    python_type = getattr(getattr(column, "type", None), "python_type", None)
    if python_type is None or isinstance(value, python_type):
        return value
    try:
        return python_type(value)
    except (TypeError, ValueError):
        # Not convertible: leave it alone and let the comparison find nothing,
        # which the caller records as "no matching row" rather than an error.
        return value


def _tenant_scope(target: WriteBackTarget, *, tenant_id: str) -> Any:
    """The value this target's rows are scoped by on their tenant column.

    **Not necessarily ADR-0001's seam string.** That seam ("default") is Core's
    own value space; a table an instance DDL-imported may key tenancy on
    something else entirely — tabsii's `tabsii.leads.tenant_id` is a UUID FK to
    `tabsii.tenants`, which is exactly what `require_tabsii_tenant_context`
    exists to resolve for the request path.

    So the target's own declaration wins: whatever `derived` says fills the
    tenant column on a create is what an update must match on. Falling back to
    the seam keeps a target that declares nothing behaving as before.

    A create never needed this — it applies every derived value when building
    the row — which is why only the update path was wrong.
    """
    for derived in target.derived:
        if derived.column != "tenant_id":
            continue
        if derived.kind == "literal":
            return derived.value
        if derived.kind == "from_tenant":
            return tenant_id
    return tenant_id


def _apply_overwrite(column: WriteBackColumn, existing: Any, incoming: Any) -> Any:
    """What an update writes, given what is already there.

    ``if_empty`` (the default) is the reason this exists: an agent enriching a
    record must not clobber what a person typed unless the target explicitly
    says it may.
    """
    if incoming is None:
        return existing
    if column.overwrite == "always":
        return incoming
    if existing in (None, ""):
        return incoming
    if column.overwrite == "append":
        return f"{existing}\n\n{incoming}"
    return existing  # if_empty, and it isn't


async def _record(
    db: AsyncSession,
    *,
    tenant_id: str,
    run_id: str | None,
    status: str,
    response: dict[str, Any] | None = None,
    error: str | None = None,
) -> None:
    """Write the audit row. ``request`` is deliberately never populated — it
    would echo the action config, which can carry a credential (#432).

    ``response`` is normalised with ``to_jsonable_python`` because it carries the
    written row's id, and an instance's id is not necessarily a string: tabsii's
    `tabsii.*` tables use real ``UUID`` primary keys. A raw ``UUID`` in a JSON
    column raises on insert — and because the audit row is written in the same
    transaction as the business write, that failure **rolls back the successful
    write with it**. So a serialisation detail here silently undoes the feature.
    """
    if run_id is None:
        return
    db.add(
        ActionLog(
            tenant_id=tenant_id,
            run_id=run_id,
            action_type=WRITEBACK_ACTION,
            status=status,
            response=to_jsonable_python(response) if response is not None else None,
            error=error,
        )
    )
    await db.flush()


async def _deny(
    db: AsyncSession,
    *,
    tenant_id: str,
    run_id: str | None,
    definition: WorkflowDefinition | None,
    reason: str,
) -> WriteBackOutcome:
    """Record a refusal, and disable a definition that keeps being refused.

    A denial that only appears in logs is indistinguishable from a feature that
    silently stopped working, so it lands on the audit log the run history
    already reads. Repeated denials disable the rule: a workflow whose owner has
    left should stop trying, loudly, rather than emitting one denial per event
    forever.
    """
    logger.warning("Write-back denied", extra={"agent_run_id": run_id, "reason": reason})
    await _record(db, tenant_id=tenant_id, run_id=run_id, status="failed", error=reason)
    if definition is not None:
        # Read once per call, so the query's limit and the comparison below can
        # never disagree — a re-read between them would be a silent off-by-one.
        threshold = settings.writeback_max_consecutive_denials
        recent = await db.execute(
            select(ActionLog)
            .where(
                ActionLog.tenant_id == tenant_id,
                ActionLog.action_type == WRITEBACK_ACTION,
            )
            .order_by(ActionLog.created_at.desc())
            .limit(threshold)
        )
        rows = list(recent.scalars())
        if len(rows) >= threshold and all(r.status == "failed" for r in rows):
            definition.enabled = False
            await db.flush()
            logger.warning(
                "Write-back workflow disabled after consecutive denials",
                extra={"definition_id": definition.id},
            )
    return WriteBackOutcome(status="denied", run_id=run_id, reason=reason)


async def _resolve_definition(
    db: AsyncSession, *, tenant_id: str, run: AgentRun
) -> WorkflowDefinition | None:
    """The definition that requested this run, via its orchestration run.

    ``None`` when the chain is broken — the agent run was created outside a
    workflow, or the definition has since been deleted. Either way there is no
    principal to act as, so the caller denies rather than guessing one.
    """
    if not run.workflow_run_id:
        return None
    workflow_run = (
        await db.execute(
            select(WorkflowRun).where(
                WorkflowRun.tenant_id == tenant_id, WorkflowRun.id == run.workflow_run_id
            )
        )
    ).scalar_one_or_none()
    if workflow_run is None:
        return None
    return (
        await db.execute(
            select(WorkflowDefinition).where(
                WorkflowDefinition.tenant_id == tenant_id,
                WorkflowDefinition.id == workflow_run.definition_id,
            )
        )
    ).scalar_one_or_none()


async def _claim(
    db: AsyncSession,
    *,
    tenant_id: str,
    definition_id: str,
    agent_run_id: str,
    event: dict[str, Any],
) -> tuple[WorkflowRun, bool]:
    """Create-or-get the run recording this write-back. ``(run, created)``.

    Same SAVEPOINT idiom as the orchestration claim: a duplicate rolls back only
    the insert, and the existing run comes back with ``created=False`` so the
    caller writes nothing a second time.
    """
    key = _dedupe_key(agent_run_id)
    run = WorkflowRun(
        tenant_id=tenant_id,
        definition_id=definition_id,
        dedupe_key=key,
        trigger_event=event,
        status="dispatched",
    )
    try:
        async with db.begin_nested():
            db.add(run)
            await db.flush()
    except IntegrityError:
        existing = await db.execute(
            select(WorkflowRun).where(
                WorkflowRun.tenant_id == tenant_id, WorkflowRun.dedupe_key == key
            )
        )
        return existing.scalar_one(), False
    return run, True


def _emit_state_change(
    db: AsyncSession,
    *,
    target: WriteBackTarget,
    operation: str,
    tenant_id: str,
    row: Any,
    agent_run: AgentRun,
) -> None:
    """Emit the table's state-change event, carrying the causation chain.

    Reuses the generic-CRUD emitter so the payload is the same full-row,
    secret-denylisted shape every other mutation produces — a consumer cannot
    tell an agent's write from a person's, which is right: it is the same
    mutation.

    The chain is the addition that matters. A workflow that writes a lead and is
    itself triggered by ``leads.created`` would otherwise cycle; inheriting
    ``causation_id`` and ``depth + 1`` from the agent run puts that loop under
    ADR-0014 §8's existing depth ceiling instead of leaving it unbounded.
    """
    op = "created" if operation == "create" else "updated"
    payload = _event_payload_for(target, row)
    payload.update(
        {
            "causation_id": agent_run.causation_id or agent_run.id,
            "depth": agent_run.depth + 1,
            "written_by": "agent",
        }
    )
    _emit_crud_event(db, target.model, op, tenant_id, row=row, payload=payload)


def _event_payload_for(target: WriteBackTarget, row: Any) -> dict[str, Any]:
    """The row as the CRUD emitter would serialise it."""
    exclude = frozenset(getattr(target.model, "__event_exclude__", ()) or ())
    return _event_payload(row, exclude)


async def execute_writeback(
    db: AsyncSession,
    *,
    tenant_id: str,
    agent_run_id: str,
    principal_names: frozenset[str],
) -> WriteBackOutcome:
    """Record a completed agent run's result into its declared target.

    Everything but ``agent_run_id`` comes from stored state; see the module
    docstring for why. Raises :class:`WriteBackNotFoundError` for anything this
    caller must not be able to distinguish from a nonexistent run.
    """
    agent_run = (
        await db.execute(
            select(AgentRun).where(AgentRun.tenant_id == tenant_id, AgentRun.id == agent_run_id)
        )
    ).scalar_one_or_none()
    if agent_run is None:
        raise WriteBackNotFoundError(agent_run_id)

    if agent_run.status != "completed":
        return WriteBackOutcome(status="skipped", reason="the run did not succeed")

    declared = (agent_run.definition_snapshot or {}).get("writeback")
    if not isinstance(declared, dict) or not declared:
        return WriteBackOutcome(status="skipped", reason="the run declared no write-back")

    target = resolve_writeback_target(str(declared.get("table") or ""))
    # An ungranted or unregistered target must look nonexistent, so a plugin the
    # table never named cannot even learn that it exists.
    if target is None or not target.allows(principal_names):
        raise WriteBackNotFoundError(agent_run_id)

    operation = str(declared.get("operation") or "create")
    if operation not in target.operations:
        return await _deny(
            db,
            tenant_id=tenant_id,
            run_id=None,
            definition=None,
            reason=f"{target.label} does not allow {operation}",
        )

    definition = await _resolve_definition(db, tenant_id=tenant_id, run=agent_run)
    if definition is None:
        return WriteBackOutcome(
            status="skipped",
            reason="the workflow that requested this run no longer exists",
        )

    # ── Authority ────────────────────────────────────────────────────────────
    run_as = definition.run_as_user_id
    if not run_as:
        return await _deny(
            db,
            tenant_id=tenant_id,
            run_id=None,
            definition=definition,
            reason="the workflow records no owner, so the write has no authority to run under",
        )

    # Re-check the author's *current* permissions. This is not the authorization
    # — the row policies are — but it turns the common refusal into a legible
    # message instead of a raw policy violation. An empty set means this
    # deployment does not model permissions this way (the default provider
    # returns one for everybody), so it is not read as a denial: absence of
    # evidence is not evidence of absence, and the policies still decide.
    permissions = await get_identity_provider().resolve_permissions(db, run_as)
    if permissions and target.permission_code not in permissions:
        return await _deny(
            db,
            tenant_id=tenant_id,
            run_id=None,
            definition=definition,
            reason=(
                f"the workflow's owner no longer has permission to write to {target.label} "
                f"({target.permission_code})"
            ),
        )

    # ── Claim, then write ────────────────────────────────────────────────────
    workflow_run, created = await _claim(
        db,
        tenant_id=tenant_id,
        definition_id=definition.id,
        agent_run_id=agent_run_id,
        event=agent_run.input_payload or {},
    )
    if not created:
        return WriteBackOutcome(
            status="duplicate",
            run_id=workflow_run.id,
            reason="this run has already been recorded",
        )

    submitted = _submitted_values(agent_run)
    allowed = {c.name for c in target.columns if c.name in declared.get("columns", {})}
    values = {
        column.name: _coerce(column, submitted.get(column.name))
        for column in target.columns
        if column.name in allowed
    }
    if not any(v is not None for v in values.values()):
        # Every mapped column resolved to nothing. The row would be "updated"
        # with no change, and calling that a success is how a silently broken
        # result shape looks exactly like a working feature — which is precisely
        # what it did look like until an E2E compared the row afterwards.
        return await _deny(
            db,
            tenant_id=tenant_id,
            run_id=workflow_run.id,
            definition=definition,
            reason=(
                "the agent returned no value for any mapped column — nothing to write "
                f"(result carried: {sorted(submitted)})"
            ),
        )

    missing = [
        c.name
        for c in target.columns
        if c.required and c.name in allowed and not values.get(c.name)
    ]
    if missing:
        return await _deny(
            db,
            tenant_id=tenant_id,
            run_id=workflow_run.id,
            definition=definition,
            reason=f"the agent returned no value for required column(s) {missing}",
        )

    # The session must act as the stored author before anything is written. A
    # refusal — including the template's own default, which has no row-level
    # security to bind to — aborts here rather than writing on an unbound session
    # where no policy would scope it.
    if not await bind_principal_session(db, run_as):
        return await _deny(
            db,
            tenant_id=tenant_id,
            run_id=workflow_run.id,
            definition=definition,
            reason=(
                "this deployment cannot bind a database session to the workflow's owner, "
                "so the write could not be authorized"
            ),
        )

    event_payload = agent_run.input_payload or {}
    missing = missing_payload_derivations(target, event_payload) if operation == "create" else []
    if missing:
        return await _deny(
            db,
            tenant_id=tenant_id,
            run_id=workflow_run.id,
            definition=definition,
            reason=(
                "the trigger event carries no "
                + ", ".join(missing)
                + " for this write-back to belong to"
            ),
        )

    try:
        if operation == "create":
            row = await _create_row(
                db,
                target=target,
                tenant_id=tenant_id,
                scope=definition.scope,
                values=values,
                event=event_payload,
            )
        else:
            row = await _update_row(
                db,
                target=target,
                tenant_id=tenant_id,
                values=values,
                event=event_payload,
            )
    except SQLAlchemyError as exc:
        # A row policy refusing the write arrives here (PostgreSQL 42501). It is
        # the expected outcome when the owner's authority has been taken away,
        # so it is a recorded denial, not a 500.
        return await _deny(
            db,
            tenant_id=tenant_id,
            run_id=workflow_run.id,
            definition=definition,
            reason=(
                f"the database refused the write for the workflow's owner: {exc.__class__.__name__}"
            ),
        )

    if row is None:
        return await _deny(
            db,
            tenant_id=tenant_id,
            run_id=workflow_run.id,
            definition=definition,
            reason="no matching row the workflow's owner is allowed to see",
        )

    _emit_state_change(
        db,
        target=target,
        operation=operation,
        tenant_id=tenant_id,
        row=row,
        agent_run=agent_run,
    )
    # Stringified for the same reason ``_record`` normalises its payload: an
    # instance's row id may be a UUID, and this value travels into JSON.
    row_id = getattr(row, "id", None)
    row_id = str(row_id) if row_id is not None else None
    workflow_run.status = "succeeded"
    # Scrub the identifying values now that they are in the product row (#673).
    #
    # Here, and NOT at completion, which is where ADR-0027 and #673 both suggested
    # putting it. `apply_writeback` reads `run.result` — `_submitted_values` above,
    # after the AGENT_RUN_COMPLETED event — so redacting at completion would leave
    # nothing to write and break the feature it is protecting. The values have to
    # survive until exactly here.
    #
    # Consequence worth stating: a run that is DENIED or fails keeps its values,
    # because they were never written anywhere else and the run record is then the
    # only evidence of what was attempted. Scrubbing a failed run would destroy the
    # audit trail to protect data that has not left the record.
    _redact_written_values(agent_run, target)
    await _record(
        db,
        tenant_id=tenant_id,
        run_id=workflow_run.id,
        status="succeeded",
        response={"table": target.table, "operation": operation, "row_id": row_id},
    )
    return WriteBackOutcome(status="written", run_id=workflow_run.id, row_id=row_id)


#: What replaces a redacted value, rather than dropping the key.
#:
#: The key stays so the run record still shows WHICH columns were written — that is
#: the explainability the record exists for. Dropping the key would make a redacted
#: write indistinguishable from a column the agent never submitted.
REDACTED_PLACEHOLDER = "[redacted]"


def _redact_written_values(agent_run: AgentRun, target: WriteBackTarget) -> None:
    """Replace written identifying values in ``AgentRun.result`` with a placeholder.

    Mutates and reassigns `result` rather than editing in place: SQLAlchemy tracks
    JSON columns by identity, so an in-place `dict` edit is not seen as a change and
    would never be flushed. That failure would be silent and would look exactly like
    redaction working.
    """
    redact = redactable_columns(target)
    if not redact:
        return
    result = agent_run.result
    if not isinstance(result, dict):
        return

    def _scrub(values: dict[str, Any]) -> dict[str, Any]:
        return {
            key: (REDACTED_PLACEHOLDER if key in redact and value is not None else value)
            for key, value in values.items()
        }

    # BOTH shapes `_submitted_values` reads, or the redaction silently does nothing
    # for one of them — which is worse than not having it, because it looks present.
    # Caught by a test seeded with the back-compat shape: the write succeeded, the
    # row held the value, and so did the run record.
    arguments = result.get("arguments")
    if isinstance(arguments, dict):
        agent_run.result = {**result, "arguments": _scrub(arguments)}
        return
    if "output" in result:
        # Prose completion: carries no columns, so there is nothing to scrub.
        return
    agent_run.result = {
        **{k: v for k, v in result.items() if k in _RUN_METADATA_KEYS},
        **_scrub({k: v for k, v in result.items() if k not in _RUN_METADATA_KEYS}),
    }


def missing_payload_derivations(target: WriteBackTarget, event: dict[str, Any] | None) -> list[str]:
    """Columns the target derives from the trigger event that the event lacks.

    Checked *before* the insert so the refusal names the missing field, rather
    than surfacing as a NOT NULL violation the author has to decode — and so a
    row is never half-written from a payload that could not identify its parent.
    """
    payload = event or {}
    return sorted(
        derived.column
        for derived in target.derived
        if derived.kind == "from_payload" and payload.get(derived.payload_field or "") in (None, "")
    )


async def _create_row(
    db: AsyncSession,
    *,
    target: WriteBackTarget,
    tenant_id: str,
    scope: dict[str, Any] | None,
    values: dict[str, Any],
    event: dict[str, Any] | None = None,
) -> Any:
    """Insert, with Core-set columns taken from trusted state, never the model."""
    fields = {name: value for name, value in values.items() if value is not None}
    for derived in target.derived:
        resolved = await _derived_value(
            derived, db=db, tenant_id=tenant_id, scope=scope, event=event
        )
        if resolved is not None:
            fields[derived.column] = resolved
    row = target.model(**fields)
    db.add(row)
    await db.flush()
    # Refresh before the caller serialises it for the state-change event: a
    # flushed instance can still hold expired attributes, and reading one during
    # payload building would lazy-load outside the async context.
    await db.refresh(row)
    return row


async def _update_row(
    db: AsyncSession,
    *,
    target: WriteBackTarget,
    tenant_id: str,
    values: dict[str, Any],
    event: dict[str, Any],
) -> Any:
    """Amend the row the *trigger event* identified — never one the agent chose.

    Selection runs on the bound session, so an instance's row policies decide
    which rows exist at all: a row the owner cannot see is simply not found, and
    the caller records a denial rather than writing.
    """
    selector = target.row_selector
    if selector is None:  # pragma: no cover — registration refuses this
        return None
    row_id = event.get(selector.payload_field)
    if not row_id:
        return None
    column = getattr(target.model, selector.column)
    row_id = _coerce_selector(column, row_id)
    row = (
        await db.execute(
            select(target.model).where(
                target.model.tenant_id == _tenant_scope(target, tenant_id=tenant_id),  # type: ignore[attr-defined]
                column == row_id,
            )
        )
    ).scalar_one_or_none()
    if row is None:
        return None
    for spec in target.columns:
        if spec.name not in values:
            continue
        merged = _apply_overwrite(spec, getattr(row, spec.name, None), values[spec.name])
        setattr(row, spec.name, merged)
    await db.flush()
    await db.refresh(row)
    return row
