#!/usr/bin/env sh
#
# Install hook dispatchers into the repository's **shared** hooks directory, so
# every worktree is guarded — including ones that already exist.
#
# ## Why not core.hooksPath
#
# #838 moved the hooks into a tracked `.githooks/` and pointed
# `core.hooksPath` there. That fixed the original bug (a gitignored runner
# directory that only `pnpm install` created), but it leaves a gap that matters
# for reaching full coverage:
#
# `core.hooksPath` is a **relative** path resolved against each worktree's root,
# and it lives in the shared config. So the moment it is set, every worktree
# checked out on a branch that predates `.githooks/` has the config but not the
# directory — and git is back to skipping silently. AGENTS.md forbids modifying
# a worktree you did not create, so those cannot simply be rebased.
#
# Git's own default is better than the override. With `core.hooksPath` **unset**,
# a linked worktree runs the hooks in the **common** `.git/hooks` directory —
# verified 2026-07-29: a dispatcher installed once in the main checkout fired in
# a pre-existing linked worktree and in one created afterwards, blocking the
# commit in both, with the hook's `pwd` set to the worktree.
#
# So the shared directory is the delivery mechanism and `.githooks/` stays the
# source of truth for the logic. One install per clone arms every worktree that
# clone will ever have.
#
# ## What a dispatcher does when there is nothing to dispatch to
#
# It warns and exits 0. A branch without `.githooks/` has no repo-defined hooks,
# which is the state it was already in — blocking every commit there would be
# inventing a gate that branch never had, and would break other agents
# mid-flight. But it says so, every time, because "no checks ran" being
# invisible is the whole defect (#838, #839).
#
# Run by `prepare`, so `pnpm install` is still what arms a fresh clone. There is
# no way to ship an armed hook in a repository — that is git's design, not an
# oversight — so the goal is to need it once per clone rather than once per
# worktree.

set -eu

HOOKS_DIR="$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null)/hooks"
mkdir -p "$HOOKS_DIR"

# An inherited core.hooksPath would make every dispatcher below unreachable, and
# the failure would be silent. Clearing it is the entire point of the exercise.
if [ -n "$(git config --local core.hooksPath 2>/dev/null || true)" ]; then
  git config --local --unset core.hooksPath
fi

for hook in pre-commit pre-push commit-msg; do
  cat > "$HOOKS_DIR/$hook" <<EOF
#!/usr/bin/env sh
# Generated by scripts/install-hooks.sh — do not edit.
# The logic lives in the tracked .githooks/ of whichever worktree is running.
root=\$(git rev-parse --show-toplevel 2>/dev/null) || exit 0
if [ -x "\$root/.githooks/$hook" ]; then
  exec "\$root/.githooks/$hook" "\$@"
fi
if [ -f "\$root/.githooks/$hook" ]; then
  exec sh "\$root/.githooks/$hook" "\$@"
fi
# Nothing to run. Say so — an unguarded commit that looks guarded is the defect
# this whole mechanism exists to remove (#839).
echo "warning: no .githooks/$hook in \$root — this tree predates the local-gate" >&2
echo "         standard, so NO checks ran. See docs/practices/standards/local-gates.md" >&2
exit 0
EOF
  chmod +x "$HOOKS_DIR/$hook"
done

echo "hooks armed: $HOOKS_DIR (shared — every worktree of this clone, now and later)"
