terraform {
  required_version = ">= 1.9"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    http = {
      source  = "hashicorp/http"
      version = "~> 3.4"
    }
  }

  # Bucket/key/region supplied at `terraform init -backend-config=backend.hcl`
  # time (generated by CI, or by `biffo sibling create`'s bootstrap step for
  # local dev) — never committed. Matches the core project's own convention.
  backend "s3" {}
}

provider "aws" {
  region = var.aws_region
}
