import type { PluginManifest } from '../plugin-manifest.js'
import { mintDevToken } from './dev-auth.js'

/**
 * The composition's self-check (biffo-template#1522 Q2, #1525): a manifest-declared
 * route must answer with the minted token, and — the control that gives that any
 * meaning — a route that does NOT exist must 404 with the SAME token on the SAME
 * prefix. A 401 row alone proves nothing (auth can reject before routing); the
 * 200/404 pair is what shows the router answered. Wrong-key and expired tokens are
 * controls in the other direction: they must be refused.
 */
export interface Probe {
  label: string
  expect: number
  method?: string
  url: string
  token?: string
}
export interface ProbeResult {
  label: string
  expect: number
  got: number | 'error'
  ok: boolean
}

export interface ProbeContext {
  coreUrl: string
  hostUrl: string
  manifest: PluginManifest
  adminToken: string
  privateKeyPem: string
  /** A token signed by a DIFFERENT key — generated by the caller. */
  wrongKeyToken: string
}

/** Declared GET routes with no path parameter — the ones a probe can call blind. */
export function probeableRoutes(manifest: PluginManifest): string[] {
  return manifest.api_routes
    .filter((r) => r.method === 'GET' && !r.path.includes('{'))
    .map((r) => r.path)
}

export function buildProbes(ctx: ProbeContext): { probes: Probe[]; notes: string[] } {
  const name = ctx.manifest.name
  const routes = probeableRoutes(ctx.manifest)
  const notes: string[] = []
  const core = (path: string) => `${ctx.coreUrl}/api/v1/plugins/${name}${path}`
  const host = (path: string) => `${ctx.hostUrl}/${name}${path}`
  const bad = `/no-such-route-${Math.random().toString(36).slice(2, 8)}`
  const expired = mintDevToken(ctx.privateKeyPem, { groups: ['admin'], ttlSeconds: -60 })
  const probes: Probe[] = [
    { label: 'core health (no auth)', expect: 200, url: `${ctx.coreUrl}/api/v1/health` },
  ]

  if (routes.length === 0) {
    notes.push(
      ctx.manifest.api_routes.length === 0
        ? 'manifest declares no api_routes: no real-route probe (nothing to reach)'
        : 'manifest declares api_routes but none is a GET without path parameters: real-route probes NOT run',
    )
  } else {
    const r = routes[0] as string
    probes.push(
      { label: `REAL ${r} via core, no token`, expect: 401, url: core(r) },
      {
        label: `REAL ${r} via core, minted token`,
        expect: 200,
        url: core(r),
        token: ctx.adminToken,
      },
      {
        label: `REAL ${r} via host, minted token`,
        expect: 200,
        url: host(r),
        token: ctx.adminToken,
      },
      {
        label: `REAL ${r} via core, wrong-key token`,
        expect: 401,
        url: core(r),
        token: ctx.wrongKeyToken,
      },
      { label: `REAL ${r} via core, expired token`, expect: 401, url: core(r), token: expired },
    )
  }
  // Controls: same prefix, same valid token as the 200s above — only the route is absent.
  probes.push(
    {
      label: `BAD  ${bad} via core, minted token`,
      expect: 404,
      url: core(bad),
      token: ctx.adminToken,
    },
    {
      label: `BAD  ${bad} via host, minted token`,
      expect: 404,
      url: host(bad),
      token: ctx.adminToken,
    },
  )
  return { probes, notes }
}

export async function runProbes(probes: Probe[], fetchFn: typeof fetch): Promise<ProbeResult[]> {
  const results: ProbeResult[] = []
  for (const p of probes) {
    let got: number | 'error'
    try {
      const res = await fetchFn(p.url, {
        method: p.method ?? 'GET',
        headers: p.token ? { authorization: `Bearer ${p.token}` } : {},
      })
      got = res.status
    } catch {
      got = 'error'
    }
    results.push({ label: p.label, expect: p.expect, got, ok: got === p.expect })
  }
  return results
}

/**
 * Green only if EVERY probe matched AND — when the manifest declares a probeable
 * route — the real-route probes were actually built. An empty real-route set for a
 * manifest that has routes is not a pass (#1363's shape: a denominator that
 * shrank silently), so the caller prints `n/n` and this refuses a vacuous green.
 */
export function probesGreen(
  results: ProbeResult[],
  manifest: PluginManifest,
): { ok: boolean; reason?: string } {
  if (results.length === 0) return { ok: false, reason: 'no probes ran' }
  const failed = results.filter((r) => !r.ok)
  if (failed.length > 0)
    return { ok: false, reason: `${failed.length}/${results.length} probe(s) failed` }
  const realRan = results.some((r) => r.label.startsWith('REAL'))
  if (!realRan && manifest.api_routes.length > 0) {
    return {
      ok: false,
      reason:
        'the manifest declares routes but no real-route probe ran (no GET without path params)',
    }
  }
  return { ok: true }
}
