/**
 * The three tiny Python entry points the composition runs. They are embedded as
 * strings and written to the run's work directory rather than shipped as files:
 * the CLI resolves companion assets by walking up from its own module, and a new
 * file needs a `PACKAGED_ROOT_ASSETS` entry or it breaks only on a real npm
 * install (#259/#315). A string constant has no such second half to forget.
 */

/**
 * Core ASGI app: the UNMODIFIED `api.main.app` wrapped by one local seam.
 *
 * API Gateway's `AWS_IAM` authorizer is what Core's `/internal/*` guard reads
 * (`request.scope["aws.event"]…iam.userArn`, Mangum-only). Under uvicorn nothing
 * sets it, so every SigV4-signed host→Core call would 401. This shim sets it
 * when — and only when — the request carries a SigV4 `Authorization` header.
 * IT DOES NOT VERIFY THE SIGNATURE (that is API Gateway's job): locally Core can
 * prove the allowlist and the user-token requirement, not the IAM layer itself.
 */
export const CORE_APP_PY = `"""Generated by biffo dev up / plugin verify (biffo-template#1525)."""
import os

from api.main import app


class LocalIamShim:
    def __init__(self, inner):
        self.inner = inner
        self.arn = os.environ["BIFFO_DEV_IAM_ARN"].encode()

    async def __call__(self, scope, receive, send):
        if scope["type"] == "http":
            headers = dict(scope["headers"])
            if headers.get(b"authorization", b"").startswith(b"AWS4-HMAC-SHA256"):
                scope["aws.event"] = {
                    "requestContext": {"authorizer": {"iam": {"userArn": self.arn.decode()}}}
                }
        await self.inner(scope, receive, send)


core_app = LocalIamShim(app)
`

/** The real shared host: real Cognito authorizer, real SigV4 sender to Core. */
export const HOST_APP_PY = `"""Generated by biffo dev up / plugin verify (biffo-template#1525)."""
import os

from plugin_host.app import build_plugin_host, core_sender

host_app = build_plugin_host(
    os.environ["BIFFO_PLUGINS_ROOT"], send_to_core=core_sender(os.environ["BIFFO_CORE_API_URL"])
)
`

/**
 * Runs in Core's own environment: builds the plugin's tables on the database via
 * the REAL plugin-migration generator, into a DISPOSABLE copy of Core's
 * `migrations/` (the generator writes into a git-tracked directory; the spike's
 * blocker 2 — the Core checkout must never be dirtied), then `alembic upgrade head`.
 */
export const BOOTSTRAP_PY = `"""Generated by biffo dev up / plugin verify (biffo-template#1525)."""
import shutil
import sys
from pathlib import Path

work, services_root = Path(sys.argv[1]), Path(sys.argv[2])
sys.path.insert(0, str(Path.cwd()))
sys.path.insert(0, str(Path.cwd() / "src"))

from alembic import command  # noqa: E402
from alembic.config import Config  # noqa: E402

from api.migrations.plugin_migrations import sync_plugin_migrations  # noqa: E402

migrations = work / "migrations"
shutil.copytree(Path.cwd() / "migrations", migrations, dirs_exist_ok=True)
generated = sync_plugin_migrations(migrations / "versions", services_root=services_root, only=None)
print(f"bootstrap: generated {len(generated)} plugin migration(s)", flush=True)
cfg = Config(str(Path.cwd() / "alembic.ini"))
cfg.set_main_option("script_location", str(migrations))

# \`plugin verify\` provisions the plugin's manifest tables before Core boots, so the generated
# plugin migration (plain op.create_table) would collide with them. Make table/column/index
# creation idempotent for this disposable bootstrap run only.
import sqlalchemy as sa  # noqa: E402
from alembic import op  # noqa: E402

_create_table, _create_index, _add_column = op.create_table, op.create_index, op.add_column
_skipped_tables: set = set()


def _insp():
    return sa.inspect(op.get_bind())


def _create_table_if_absent(name, *args, **kw):
    if _insp().has_table(name, schema=kw.get("schema")):
        _skipped_tables.add(name)
        return None
    return _create_table(name, *args, **kw)


def _create_index_if_absent(name, table, *args, **kw):
    if table in _skipped_tables:
        return None
    return _create_index(name, table, *args, **kw)


def _add_column_if_absent(table, column, **kw):
    if any(c["name"] == column.name for c in _insp().get_columns(table, schema=kw.get("schema"))):
        return None
    return _add_column(table, column, **kw)


op.create_table = _create_table_if_absent
op.create_index = _create_index_if_absent
op.add_column = _add_column_if_absent

command.upgrade(cfg, "head")
print("bootstrap: alembic upgrade head complete", flush=True)
`
